spring:
  application:
    name:  application-spring-cloud-eureka
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qq1026290752/yulece-config
eureka:
  instance:
    prefer-ip-address: true