apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: spring-cloud-config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      namespace: dev
      app: spring-cloud-config-service
  template:
    metadata:
      labels:
         namespace: dev
         app: spring-cloud-config-service
    spec:
      containers:
      - name: spring-cloud-config-service
        imagePullPolicy: Always
        image: registry.cn-beijing.aliyuncs.com/application-spring-cloud/spring-cloud-config-service:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-config-service
  namespace: dev
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
  selector:
    namespace: dev
    app: spring-cloud-config-service